### ISSUE TITLE
training succeed, and met the problem.

### ISSUE THREAD

**Issue by smallsmallwood** [text-machine-lab/entity-coref#1]
No entities found in file: bc/phoenix/00/phoenix_0003-0
No entities found in file: bc/msnbc/00/msnbc_0007-11
No entities found in file: bc/phoenix/00/phoenix_0003-1
No entities found in file: bc/phoenix/00/phoenix_0003-2
No entities found in file: bc/phoenix/00/phoenix_0003-4
No entities found in file: bc/phoenix/00/phoenix_0003-5
No entities found in file: bc/phoenix/00/phoenix_0003-3
No entities found in file: bc/cnn/00/cnn_0008-0
No entities found in file: bc/cnn/00/cnn_0008-1
No entities found in file: bc/phoenix/00/phoenix_0003-6
No entities found in file: bc/cnn/00/cnn_0008-3
No entities found in file: bc/cnn/00/cnn_0008-2
No entities found in file: bc/cnn/00/cnn_0008-6
No entities found in file: bc/cnn/00/cnn_0008-8
No entities found in file: bc/cnn/00/cnn_0008-4
No entities found in file: bc/cnn/00/cnn_0008-7
No entities found in file: bc/cnn/00/cnn_0008-5
No entities found in file: bc/cnn/00/cnn_0008-9
No entities found in file: bc/cnn/00/cnn_0008-13
No entities found in file: bc/cnn/00/cnn_0008-12
No entities found in file: bc/cnn/00/cnn_0008-10
No entities found in file: bc/cnn/00/cnn_0008-15
No entities found in file: bc/cnn/00/cnn_0008-11
No entities found in file: bc/cnn/00/cnn_0008-14
Completed saving results!
Pairwise evaluation:
True histogram (array([0, 0, 0, 0]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))
Prediction histogram (array([0, 0, 0, 0]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))
No entities found in file: mz/sinorama/10/ectb_1009-0
No entities found in file: mz/sinorama/10/ectb_1009-3
No entities found in file: mz/sinorama/10/ectb_1009-1
Traceback (most recent call last):
  File "predict.py", line 126, in <module>
    main()
  File "predict.py", line 110, in main
    clustering_only=args.clustering_only, compute_linkage=args.compute_linkage)
  File "/home/wlk/entity-coref-master/src/evaluator.py", line 295, in write_results
    print(classification_report(all_pairs_true, np.round(all_pairs_pred), digits=3))
  File "/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py", line 1568, in classification_report
    name_width = max(len(cn) for cn in target_names)
ValueError: max() arg is an empty sequence

**Comment by ylmeng** [comment]
Does this happen to all test files? Did you check the files to make sure there are tagged entities?
Just to remind you this code only works for files with tagged entities, not blank files.

**Comment by smallsmallwood** [comment]
Thanks, I find the last column containing coreference information is set to "-" in all test files, and can you tell me how to solve it.

**Comment by ylmeng** [comment]
You can use it on the test files with "true entities", which are provided by the organizer.
Otherwise you need to use an entity tagger. 
If you just want to see how it works, you can also spare some training files for testing.

**Comment by smallsmallwood** [comment]
I need to create “raw_results”, "linkages", "true-linkages", "responses", "key.tmp" in result_dir/ by myself,right?

**Comment by ylmeng** [comment]
key.tmp is just a combined test (truth) file. You can just concatenate all the test files to make it one file. Or you can uncomment the lines in function scorer() in predict.py so it will be generated at testing time.

“raw_results”, "linkages", "true-linkages", and "responses" are all generated by predict.py automatically. You do not need to provide them.

The point here is that you need to have annotated entities in your test files (with brackets in the right-most column). All the intermediate files are handled by the predict script, specifically in ‘src/evaluator.py’
